name: Bug report
description: Report a bug in the app or project itself
labels: bug, triage
body:
- type: markdown
  attributes:
    value: |
      Thanks for taking the time to fill out this bug report!
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the bug you encountered.
    options:
    - label: I have searched the existing issues
      required: true
- type: checkboxes
  attributes:
    label: Are you sure this is NOT an issue about external scripts not working?
    description: Please replace and choose the correct type for issues about third-party user scripts.
    options:
    - label: I am sure it is NOT a user script issue
      required: true
- type: textarea
  attributes:
    label: Current Behavior
    description: A concise description of what you're experiencing.
  validations:
    required: false
- type: textarea
  attributes:
    label: Expected Behavior
    description: A concise description of what you expected to happen.
  validations:
    required: false
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: Steps to reproduce the behavior.
    placeholder: |
      1. In this environment...
      2. With this config...
      3. Run '...'
      4. See error...
  validations:
    required: false
- type: checkboxes
  id: platform
  attributes:
    label: OS (Device)
    description: In which operating systems did you test this issue?
    options:
    - label: macOS (Mac)
    - label: iOS (iPhone)
    - label: iPadOS (iPad)
- type: textarea
  attributes:
    label: Environment
    description: |
      examples:
        - **OS/Safari version**: macOS 13.0.1 (22A400), Safari 16.1 (18614.2.9.1.12)
        - **Userscripts version**: 4.3.3 (65)
        - **OS/Safari version**: iOS 16.1.1
        - **Userscripts version**: 1.3.3 (38)
        - **OS/Safari version**: iPadOS 16.1.1
        - **Userscripts version**: 1.3.3 (38)
    value: |
        - OS/Safari version:
        - Userscripts version:
    render: markdown
  validations:
    required: false
- type: textarea
  id: logs
  attributes:
    label: Relevant log output
    description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
    render: shell
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? References? Anything that will give us more context about the issue you are encountering!

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
